
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-happycows-s26-15
owner: ucsb-cs156-s26
repo_name: proj-happycows-s26-15
pull_requests: [{"author":{"id":"U_kgDOCWJ8dA","is_bot":false,"login":"f1amek1ller","name":"Omega"},"headRefName":"issue/34-hidden-commons-join","number":58,"title":"Prevent joining hidden commons via API endpoint","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-15/pull/58"},{"author":{"id":"U_kgDOCuio7Q","is_bot":false,"login":"joyycheng","name":"Joy Cheng"},"headRefName":"joy-courses-form","number":57,"title":"Joy courses form","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-15/pull/57"},{"author":{"id":"U_kgDOCui9WA","is_bot":false,"login":"mikaelafitz","name":""},"headRefName":"mf-happycows-crud-course","number":55,"title":"mf - happycows CRUD Course","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-15/pull/55"},{"author":{"id":"U_kgDOCxz58A","is_bot":false,"login":"schoolKris08","name":"Kristopher Rangel-Olivos"},"headRefName":"KR-ImplementFeatureFlags","number":54,"title":"KR - Implemented Feature Flags","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-15/pull/54"},{"author":{"id":"U_kgDOC5bJ1g","is_bot":false,"login":"katelyn-dang","name":""},"headRefName":"kd-announcements-on-play-page","number":53,"title":"kd - add announcements to play page","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-15/pull/53"},{"author":{"id":"U_kgDOCWJ8dA","is_bot":false,"login":"f1amek1ller","name":"Omega"},"headRefName":"issue/30-admin-chat-button","number":48,"title":"feat: add admin chat view for commons (issue #30)","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-15/pull/48"}]
